main/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from accounts.views import(
    login_view,
    register_view,
    logout_view
)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls",namespace ="comments")),
    url(r'^login/', login_view,name="login"),
    url(r'^register/', register_view, name="register"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^', include("posts.urls",namespace ="posts")),
    url(r'^api/posts/', include("posts.api.urls",namespace ="posts-api")),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/urls.py
from django.conf.urls import url
from .views import (
    PostListAPIView,
    PostDetailAPIView,
    PostUpdateAPIView,
    PostDestroyAPIView,
)

urlpatterns = [
    url(r'^$', PostListAPIView.as_view(),name='list'),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit$', PostUpdateAPIView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete$', PostDestroyAPIView.as_view(), name='delete'),
]

posts/urls.py
from django.conf.urls import url
from .views import (
    post_list,
    post_detail,
    post_create,
    post_edit,
    post_delete,
    
)

urlpatterns = [
    url(r'^$', post_list,name='list'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^create$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/edit$', post_edit, name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete$', post_delete, name='delete'),

]

posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models 
from django.db.models.signals import pre_save
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from markdown_deux import markdown
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType
# Create your models here.
# create a manger to filter the posts
class PostManager(models.Manager):
    def active(self,*args,**kwargs):
        return super(PostManager,self).filter(draft=False).filter(publish__lte = timezone.now())
# define the location of the images and files with a specific names
def upload_location(instance, filename):
    return "%s/%s" %(instance.slug, filename)
class Post (models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
    title = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, null=True,blank=True, width_field = "width_field", height_field = "height_field")
    width_field = models.IntegerField(default=0)
    height_field = models.IntegerField(default=0)           
    file = models.FileField(upload_to=upload_location,null=True,blank=True)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False,auto_now_add=False)
    Created_At = models.DateTimeField(auto_now_add = True)
    Updated_At = models.DateTimeField(auto_now = True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail",kwargs={"slug":self.slug})
    def get_absolute_url_edit(self):
        return reverse("posts:edit",kwargs={"slug":self.slug})
    def get_absolute_url_delete(self):
        return reverse("posts:delete",kwargs={"slug":self.slug})   
    
    # this function will get the pagedown content and markedown to a html form "with the balise staff" and then make it safe to disply correctly
    def get_markdown(self):
        content= self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)
    # get the comments for a specific posts 
    @property
    def comments(self):
        return Comment.objects.filter_by_instance(self)
    
    # get the Post class
    @property
    def get_content_type(self):
        return ContentType.objects.get_for_model(self.__class__)

    class Meta:
        ordering = ["-Created_At","-Updated_At"]
    #initialize the postmanager
    objects = PostManager()

def create_slug(instance,new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug 
    qs = Post.objects.filter(slug = slug).order_by("-id")
    exists = qs.exists()
    if exists :
        new_slug = "%s-%s" %(slug,qs.first().id) 
        return create_slug(instance,new_slug=new_slug)
    return slug

def pre_save_post(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post,sender=Post)

posts/forms.py
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget
class PostForm(forms.ModelForm):
    # adding pagedown to forms
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "file",
            "draft",
            "publish"      
        ]

posts/api/views.py
from rest_framework.generics import (
    DestroyAPIView,
    ListAPIView ,
    UpdateAPIView,
    RetrieveAPIView,
    
) 

from posts.models import Post
from .serializers import PostListSerializer ,PostDetailSerializer

class PostListAPIView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostListSerializer

class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'

class PostUpdateAPIView(UpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'

class PostDestroyAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'

posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse ,HttpResponseRedirect,Http404
from django.shortcuts import render , get_object_or_404 , redirect 
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from comments.models import Comment
from comments.forms import CommentForm

# Create your views here.
from .models import Post
from .forms import PostForm

def post_list (request):
    today = timezone.now().date()
    queryset =Post.objects.active()
    if request.user.is_staff or request.user.is_superuser:
        queryset =Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(user__first_name__icontains=query)|
            Q(user__last_name__icontains=query)
            ).distinct()
    paginator = Paginator(queryset, 5)
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
        "contacts":queryset,
        "today":today,
    }
    return render(request,"post_list.html",context)

def post_detail (request,slug=None):
    instance = get_object_or_404(Post,slug=slug)
    if instance.draft or instance.publish > timezone.now().date() :
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    # get the comment releated to the post
    comments = instance.comments

    initial_data = {
        "content_type" :instance.get_content_type,
        "object_id" : instance.id
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=c_type)
        object_id = form.cleaned_data.get('object_id')
        content = form.cleaned_data.get('content')
        parent_obj = None
        # cheack if there is a parent id
        try:
            parent_id =int(request.POST.get('parent_id'))
        except:
            parent_id =None
        # cheack if it exist in the db
        if parent_id :
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count()==1:
                parent_obj= parent_qs.first()
        new_comment,created = Comment.objects.get_or_create(
                                  user = request.user,
                                  content_type = content_type,
                                  object_id = object_id,
                                  content = content, 
                                  parent = parent_obj,
                                )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    if instance.file:
        t0,t1,t2,t4 = instance.file.url.split('/')
    else:
        t4 = ''
    context = {
        "title": instance.title,
        "instance": instance,
        "pdf_name": t4,
        "comments":comments,
        "comment_form":form,
    }
    return render(request,"comment_style.html",context)
    
@login_required(login_url='/login/')
def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, 'Post created.')
        return redirect("posts:list")
    else :
        messages.error(request, 'Post Not created.')
    context={
        "form":form,
    }
    return render(request,"post_form.html",context)

@login_required(login_url='/login/')
def post_edit(request,slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    instance = get_object_or_404 (Post , slug =slug)
    form = PostForm(request.POST or None ,request.FILES or None, instance = instance)
    if form.is_valid():
        instance = form.save(commit =False)
        instance.save()
        messages.success(request, 'Post details updated.')
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title" : instance.title,
        "instance" : instance,
        'form' : form,
    }
    return render(request,"post_form.html",context)

@login_required(login_url='/login/')
def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    instance = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        instance.delete()
        messages.success(request,"succsessfuly deleted")
        return redirect("posts:list")
    context ={
        "object":instance
    }
    return render(request,"confirm_delete.html",context)

templates/base.html
{% load staticfiles %}

<html ng-app="supcom">
        <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1.0"/>

    <title>
        {% block head_title%}SupcomBlog{%endblock head_title%}
    </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Buttons/2.0.0/css/buttons.min.css">
    
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
    <link rel="stylesheet" href="{% static '/css/comment_style.css' %}">
    {% block head_extra%}{%endblock head_extra%}
    <body >
        
        <div  class="navbar-fixed-top ">
            <ol id="bread1" class="breadcrumb" >
                <li id="l1" style="color: #f5dd5d;font-weight: 300; font-size: 24px;">SUP'COM BLOG</li>
                {% block search%}{% endblock search%}
                
                {% if not request.user.is_authenticated%}
                <li  class="pull-right"><a href='{% url "register"%}'> Register</a></li>
                <li  class="pull-right"><a href='{% url "login"%}'> Login&nbsp;</a></li>
                {%else%}
                <li  class="pull-right"><a href='{% url "logout"%}'> Logout</a></li>
                <li class="pull-right">WELCOME, {{request.user}}</li>
                {% endif %}
                
            </ol>
            <ol id="bread2" class="breadcrumb" >
                <a href='{% url "posts:list"%}'> Home</a>
                
                {% block post_detail_link %}{% endblock post_detail_link %}
                {% block post_thread_link %}{% endblock post_thread_link %}
                {% if request.user.is_staff or request.user.is_superuser%}
                <span class="pull-right button-wrap">
                    <a href='{% url "posts:create"%}' class="button button-pill button-raised button-primary">ADD POST <strong style="font-size: 21px;">&nbsp; +</strong></a>
                </span>
                {% endif%}
            </ol>
            
        </div>
        <div id="cc" class="container" style="padding-top:4.5cm;padding-left: 0;padding-right: 0;" >
            {% include "messages_display.html" %}
            {% block content %}{% endblock content %}
        </div>
        
    
       

    <!-- js library and framework -->
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
    
    <script src="{% static '/js/google-api.js' %}"></script> 
    <script src="{% static '/js/app/app.module.js' %}"></script>
    <script src="{% static '/js/app/app.config.js' %}"></script>
    <script src="{% static '/js/app/blog-list/blog-list.module.js' %}"></script>
    <script src="{% static '/js/app/blog-list/blog-list.component.js' %}"></script>
        <script type="text/javascript">
            $(document).ready(function () { 
                // make the image inside the pagedown content responsive of each image in there
                $('.responsive-image img').each(function () {
                    $(this).addClass('img-responsive');
                })

                var titleItem = $('#id_title');
                function setTitle(value) {
                    $('#preview-title').text(value);
                }
                setTitle(titleItem.val())
                titleItem.keyup(function () {
                    newtitle = $(this).val();
                    setTitle(newtitle)
                })
                // get the content form the post form
                var contentItem = $('#id_content');

                // render to the preview
                function setContent(value) {
                    $('#preview-content').html(marked(value));
                    $('#preview-content img').each(function () {
                        $(this).addClass('img-responsive')
                    })
                }
              
                setContent(contentItem.val())
                // make it dynamic to every change
                contentItem.keyup(function () {
                    newContent = $(this).val();
                    setContent(newContent)
                })
                // toggle the reply button
                $('.comment-reply-btn').click(function (event) {
                    event.preventDefault();
                    $(this).parent().next('.comment-reply').fadeToggle();
                })

                $('.option-reply-btn').click(function (event) {
                    event.preventDefault();
                    $(this).parent().next('.option-reply').fadeToggle();
                })
             
             
            })
            
        </script>
    </body>
</html>

templates/comment_style.html
{% extends "base.html" %}
{% load crispy_forms_tags%}

{% block head_title%}{{block.super}} |   {{title}}{%endblock head_title%}

{% block post_detail_link %}
    <li> <small style="color: white"> > </small><a href="{{instance.get_absolute_url}}">{{instance.title}}</a></li>
{% endblock post_detail_link  %}
{% block content %}
<div class="row" style="padding: 0;" >
    <div class="col-sm-8 col-sm-offset-0 col-xs-10 col-xs-offset-1 " style="padding-left: 0;">
        <div class="thumbnail">
            <h1>{{title}} <small>{% if instance.draft%}<span style="color:red"> Draft</span>{%endif%} {{instance.publish}}</small></h1>
            <p>Author: {{instance.user}}</p>
            {% if instance.image %}
            <img src="{{instance.image.url}}" class="img-responsive">
            {% endif %}
        
            {% if instance.file%}
            <br>
            <button type="button" class="btn btn-aramark-primary" onclick="window.open('{{instance.file.url}}')"><span class="glyphicon glyphicon-save-file"> {{pdf_name}}</span></button>
            <hr>
            {% endif %}
            <br>
            <div class="responsive-image">{{instance.get_markdown}}</div>
            <hr>
        </div>
    </div>

    <div class="col-sm-4 col-sm-offset-0 col-xs-10 col-xs-offset-1 thumbnail" class="actionBox"  >
        <div class="titleBox"  style="border-bottom-color: gray"> 
        <label>Comment Box</label>
        {% verbatim %}
        <div ng-controller="BlogListController" >

        </div>
        {% endverbatim %}
        </div>
        <div>
            <ul class="commentList">
                {%for comment in comments%}
                <li style=" list-style-type:none">
                    <div class="commenterImage">
                        <img src="http://www.vectorsforum.com/uploads/49/viking23.png" />
                    </div>
                    <div class="commentText">
                        <p class="">{{comment.content}}</p> 
                        <span style="color:#1569C7">{{comment.user}} | On {{comment.Created_At|timesince}} ago 
                            {% if comment.children.count > 0 %}| {{comment.children.count}} comment{% if comment.children.count > 1 %}s {% endif%}{% endif%}</span>
                        <span><button class="option-reply-btn"><i class="fa fa-ellipsis-h"></i></button></span>
                        <p class="option-reply">
                            <button class="comment-reply-btn button button-large button-plain button-border button-circle "><i class="fa fa-reply"></i></button>
                            <a id="ther" href="{{comment.get_comment_url}}" class="button button-large button-plain button-border button-circle button-longshadow-left"><i class="fa fa-eye" aria-hidden="true"></i></a>                           
                            {% if request.user == comment.user%} 
                            <a id="trash" href="{{comment.get_delete_url_from_post}}" class="button button-large button-plain button-border button-circle"><i class="fa fa-trash-o"></i></a>
                            {%endif%}
                        </p>
                        <div class="comment-reply" >
                            {%for comment_children in comment.children%}
                            <div style="padding-left: 15px">
                                <br>
                            <blockquote style="border-left: 2px solid #1569C7;">
                                <div class="commenterImage">
                                    <img src="http://s207166.gridserver.com/wp-content/uploads/2015/09/Projects_Vikings_Header_Ragnar.png" />
                                </div>
                                <div class="commentText" >
                                    <p>{{comment_children.content}}</p>
                                    <footer style="color:#1569C7">{{comment_children.user}} | On {{comment_children.Created_At|timesince}} ago
                                        {% if request.user == comment_children.user%}<a id="trash" href="{{comment_children.get_delete_url_from_post}}" class="button button-large button-plain button-border button-circle"><i class="fa fa-trash-o"></i></a>{%endif%}
                                    </footer>
                                </div>
                            </blockquote>  
                            </div>  
                            
                            {%endfor%}   
                            {% if request.user.is_authenticated%}
                            <br>
                            <form class="form-inline" role="form" method="POST" action="">{%csrf_token%}
                                <div class="form-group">
                                    <input type="hidden" name="parent_id" value="{{comment.id}}">
                                        {{comment_form|crispy}}
                                </div>
                                <div class="form-group">
                                    <button class="button button-primary button-box button-small button-longshadow-right"><i class="fa fa-reply"></i></button>
                                </div>
                            </form>
                            {%else%}
                            <p>You must login to comment</p>
                            {%endif%}
                        </div>
                    </div>
                   
                </li>
                <hr> 
                {%endfor%}
            </ul>

            {% if request.user.is_authenticated%}
            <form  class="form-inline" role="form" method="POST" action="">{%csrf_token%}
                <div class="form-group">
                        {{comment_form|crispy}}
                </div>
                <div class="form-group">
                    <button class="button button-primary button-box button-small button-longshadow-right"><i class="fa fa-plus"></i></button>
                </div>
            </form>
            {%else%}
            <p>You must login to comment</p>
            {%endif%}

        </div>
    </div>
</div>
{% endblock content %}

templates/comment_thread.html
{% extends "base.html" %}
{% load crispy_forms_tags%}

{% block head_title%}{{block.super}} |   {{title}}{%endblock head_title%}
{% block post_thread_link %}
<small style="color: white"> > </small><a href="{{comment.content_object.get_absolute_url}}">{{comment.content_object}}</a>
<small style="color: white"> > </small><a href="{{comment.get_comment_url}}">{{comment.user}} comment</a>
{% endblock post_thread_link  %}
{% block content %}
<div class="col-sm-8 col-sm-offset-2 ">
    <div class="thumbnail">
        <blockquote style="border-left: 5px solid #1569C7;">
            <p>{{comment.content}}</p>
            <footer style="color:#1569C7">{{comment.user}} | On {{comment.Created_At|timesince}} ago 
                {% if comment.children.count > 0 %}| {{comment.children.count}} comment{% if comment.children.count > 1 %}s {% endif%}{% endif%}
                &nbsp;&nbsp;
                <a id="ther" href="{{comment.content_object.get_absolute_url}}" class="button button-large button-plain button-border button-circle"><i class="fa fa-address-book-o"></i></a>
                {% if request.user == comment.user%} 
                <a id="trash" href="{{comment.get_delete_url}}" class="button button-large button-plain button-border button-circle"><i class="fa fa-trash-o"></i></a>
                {%endif%}
            </footer>
            <hr>
            <div>
                {%for comment_children in comment.children%}
                <blockquote style="border-left: 5px solid #1569C7;">
                    <p>{{comment_children.content}}</p>
                    <footer style="color:#1569C7">{{comment_children.user}}
                    | On {{comment_children.Created_At|timesince}} ago &nbsp;&nbsp;
                    {% if request.user == comment_children.user%}<a id="trash" href="{{comment_children.get_delete_url}}" class="button button-large button-plain button-border button-circle"><i class="fa fa-trash-o"></i></a>{%endif%}
                </footer>
                </blockquote>    
                <hr>
                {%endfor%}   
                {% if request.user.is_authenticated%}
                <form class="form-inline" method="POST" action=""> {%csrf_token%}
                    {{comment_form|crispy}}
                    <input type="hidden" name="parent_id" value="{{comment.id}}">
                    <button class="button button-primary button-box button-small button-longshadow-right"><i class="fa fa-reply"></i></button>
                </form>
                {%else%}
                <p>You must login to comment</p>
                {%endif%}
            </div>
        </blockquote>
    </div>
</div>
{% endblock content %}

templates/confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags%}

{% block head_title%}{{block.super}} |   {{title}}{%endblock head_title%}
{% block content %}
<div class="col-sm-8 col-sm-offset-2">
    <div class="thumbnail">   
        <h1>Are you sure ?</h1>
        <hr>
        <form method="POST" action=""> {%csrf_token%}
            <p>Are you sure you want to delete: "{{ object.title}}" ?</p>
            <input type="submit"  class="btn btn-warning" value="Yes,I'm sure">
            <a href="/"  class="btn btn-default">No, take me back</a>
        </form>
    </div>
</div>
{% endblock content %}

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags%}
<!-- adding the css form of pagedown -->
{% block head_extra%}
    {{form.media}}
{%endblock head_extra%}
{% block content %}

<div class="col-sm-6 col-sm-offset-3 ">
    <div class="thumbnail">
        <h2 style="text-align: center">{{title}}</h2>
        <hr>
        <form method="POST" action="" > {%csrf_token%}
            {{form|crispy}}
            {% if title == "Submit" %}
            <button id="login" style="margin-left: 45%" type="submit"  class="btn btn-success" >{{title}}</button>
            {%else%}
            <input style="margin-left: 40%" type="submit"  class="btn btn-primary" value="{{title}}">
            {%endif%}

        </form>
    </div>
    {% if title == "Submit" %}
    <div class="thumbnail" id="result"></div>
        <a id="trash3"  class="pull-right button  button-box button-large button-longshadow-right"><i class="fa fa-microphone-slash"></i></a>        
        <a id="trash2"  class="pull-right button button-primary button-box button-large button-longshadow-right"><i class="fa fa-microphone"></i></a>
    </div>
    {%endif%}
    
</div>
{% endblock content %}

templates/messages_display.html
{% if messages %}
<div class="messages">
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

templates/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags%}

{% block head_title%}{{block.super}} |   {{title}}{%endblock head_title%}

{% block post_detail_link %}
    <li> <small style="color: white"> > </small><a href="{{instance.get_absolute_url}}">{{instance.title}}</a></li>
{% endblock post_detail_link  %}
{% block content %}
<div class="col-sm-8 col-sm-offset-2">
<div class="thumbnail">
    <h1>{{title}} <small>{% if instance.draft%}<span style="color:red"> Draft</span>{%endif%} {{instance.publish}}</small></h1>
    <p>Author: {{instance.user}}</p>
    {% if instance.image %}
    <img src="{{instance.image.url}}" class="img-responsive">
    {% endif %}
   
    {% if instance.file%}
    <br>
    <button type="button" class="btn btn-aramark-primary" onclick="window.open('{{instance.file.url}}')"><span class="glyphicon glyphicon-save-file"> {{pdf_name}}</span></button>
    <hr>
    {% endif %}
    <br>
    <div class="responsive-image">{{instance.get_markdown}}</div>
    <hr>
    <br> 
    <div>
        <h2 class="lead">  Comments</h2>
        <div>
            <div class="thumbnail">
                {% if request.user.is_authenticated%}
                <form method="POST" action=""> {%csrf_token%}
                    {{comment_form|crispy}}
                    <input type="submit"  class="btn btn-default" value="Comment Post">
                </form>
                {%else%}
                <p>You must login to comment</p>
                {%endif%}
            </div>
        </div>
        {%for comment in comments%}
        <blockquote style="border-left: 5px solid #1569C7;">
            <p>{{comment.content}}</p>
            <footer style="color:#1569C7">{{comment.user}} | On {{comment.Created_At|timesince}} ago 
                {% if comment.children.count > 0 %}| {{comment.children.count}} comment{% if comment.children.count > 1 %}s {% endif%}{% endif%}
                | <a class="comment-reply-btn" style="color: black" href="#">Reply</a>
                | <a style="color: black" href="{{comment.get_comment_url}}">Thread</a> 
                {% if request.user == comment.user%} | <a href="{{comment.get_delete_url_from_post}}">Delete</a>{%endif%}
            </footer>
            <div class="comment-reply" >
                {%for comment_children in comment.children%}
                <blockquote style="border-left: 5px solid #1569C7;">
                    <p>{{comment_children.content}}</p>
                    <footer style="color:#1569C7">{{comment_children.user}} | On {{comment_children.Created_At|timesince}} ago
                        {% if request.user == comment_children.user%} | <a href="{{comment_children.get_delete_url_from_post}}">Delete</a>{%endif%}
                    </footer>
                </blockquote>    
                <hr>
                {%endfor%}   
                {% if request.user.is_authenticated%}
                <form method="POST" action=""> {%csrf_token%}
                    {{comment_form|crispy}}
                    <input type="hidden" name="parent_id" value="{{comment.id}}">
                    <input type="submit"  class="btn btn-default" value="Reply">
                </form>
                {%else%}
                <p>You must login to comment</p>
                {%endif%}
            </div>
        </blockquote>
        <hr>
        {%endfor%}
    </div>
</div>
</div>

{% endblock content %}